### ISSUE TITLE
Add MIT license to lubot

### ISSUE THREAD

**Issue by bretself** [lansingcodes/lubot#25]

**Comment by atomaka** [comment]
@chrisvfritz Should probably sign off on license changes since he wrote the bulk of the code.

**Comment by egillespie** [comment]
@bretself checked with me and I ran it by @KatieMFritz. We don't think Chris would be concerned, but I can double-check with him before accepting the PR. Thanks for keeping an eye out for us @atomaka! 😊

**Comment by atomaka** [comment]
Yeah. I don't he cares, but good practice to check!

**Comment by egillespie** [comment]
Totes. He's cool with it.

![image](https://user-images.githubusercontent.com/5572255/46708990-8e5f8300-cc0f-11e8-9aca-209825a0ee3d.png)
